[package]
name = "pyre-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "pyre"
path = "src/main.rs"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true }
tarpc = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tokio-serde = { workspace = true }
tokio-util = { workspace = true }
clap = { version = "4", features = ["derive"] }
alacritty_terminal = { workspace = true }
pyre-proto = { path = "../pyre-proto" }
pyre-themes = { path = "../pyre-themes" }
toml = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libc = { workspace = true }
regex = { workspace = true }
