[package]
name = "pyred"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
default-run = "pyred"

[dependencies]
pyre-proto = { path = "../pyre-proto" }
tokio.workspace = true
tarpc.workspace = true
portable-pty.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
futures.workspace = true
bytes.workspace = true
tokio-util.workspace = true
tokio-serde.workspace = true
bincode.workspace = true
nix.workspace = true
uuid.workspace = true
libc.workspace = true
chrono.workspace = true
sqlx.workspace = true
zstd.workspace = true
alacritty_terminal.workspace = true
dirs.workspace = true
regex.workspace = true
async-trait.workspace = true

[dev-dependencies]
tempfile = "3"
