[package]
name = "pyred"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
default-run = "pyred"

[dependencies]
pyre-proto = { path = "../pyre-proto" }
tokio.workspace = true
tarpc.workspace = true
portable-pty.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
futures.workspace = true
bytes.workspace = true
tokio-util.workspace = true
tokio-serde.workspace = true
bincode.workspace = true
nix.workspace = true
uuid.workspace = true
libc.workspace = true
chrono.workspace = true
sqlx.workspace = true
zstd.workspace = true
alacritty_terminal.workspace = true
dirs.workspace = true
regex.workspace = true
tantivy.workspace = true
async-trait.workspace = true
toml.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
clap.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libproc = "0.14"

[dev-dependencies]
tempfile = "3"
vt100 = "0.15"
serde_bytes.workspace = true
